# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy

builds:
- id: distributor
  dir: function/distributor
  binary: xlapse-distributor
  ldflags:
  - "-s -w -X github.com/dtan4/xlapse/version.Version={{.Version}} -X github.com/dtan4/xlapse/version.Commit={{.Commit}} -X github.com/dtan4/xlapse/version.Date={{.Date}}"
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
- id: downloader
  dir: function/downloader
  binary: xlapse-downloader
  ldflags:
  - "-s -w -X github.com/dtan4/xlapse/version.Version={{.Version}} -X github.com/dtan4/xlapse/version.Commit={{.Commit}} -X github.com/dtan4/xlapse/version.Date={{.Date}}"
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
- id: gif-distributor
  dir: function/gif-distributor
  binary: xlapse-gif-distributor
  ldflags:
  - "-s -w -X github.com/dtan4/xlapse/version.Version={{.Version}} -X github.com/dtan4/xlapse/version.Commit={{.Commit}} -X github.com/dtan4/xlapse/version.Date={{.Date}}"
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
- id: gif-maker
  dir: function/gif-maker
  binary: xlapse-gif-maker
  ldflags:
  - "-s -w -X github.com/dtan4/xlapse/version.Version={{.Version}} -X github.com/dtan4/xlapse/version.Commit={{.Commit}} -X github.com/dtan4/xlapse/version.Date={{.Date}}"
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64

archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    linux: Linux
    amd64: x86_64

release:
  prerelease: auto

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
